export const TODO_GET_LIST_EFFECT = 'TODO_GET_LIST_EFFECT';
export const TODO_GET_LIST_LOADING_STATE = 'TODO_GET_LIST_LOADING_STATE';
export const TODO_GET_LIST_DATA_STATE = 'TODO_GET_LIST_DATA_STATE';
export const TODO_GET_LIST_ERROR_STATE = 'TODO_GET_LIST_ERROR_STATE';
