export const PROFILE_GET_INFO_EFFECT = 'PROFILE_GET_INFO_EFFECT';
export const PROFILE_ADD_USER_EFFECT = 'PROFILE_ADD_USER_EFFECT';

export const PROFILE_GET_INFO_LOADING_STATE = 'PROFILE_GET_INFO_LOADING_STATE';
export const PROFILE_GET_INFO_DATA_STATE = 'PROFILE_GET_INFO_DATA_STATE';
export const PROFILE_GET_INFO_ERROR_STATE = 'PROFILE_GET_INFO_ERROR_STATE';
export const PROFILE_ADD_USER_STATE = 'PROFILE_ADD_USER_STATE';
